# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.0.1
_src_path: gh:epics-containers/ioc-template
description: The Generic IOC for the positioner controller
git_platform: github.com
github_org: epics-containers
name: ioc-positioner
repo_uri: git@github.com:epics-containers/ioc-positioner.git
rtems: false
